name: SonarQube Analysis

on:
  push:
    branches:
      - "*"

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Cache SonarQube Scanner
        uses: actions/cache@v2
        with:
          path: |
            ~/.sonar/cache
          key: sonarqube-${{ runner.os }}-jdk-${{ hashFiles('**/*.gradle*', '**/*.kts*') }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.6"

      - name: Install dependencies
        run: |
          flutter upgrade --force
          flutter pub get
          flutter build apk

      - name: Build and analyze
        run: |
          sonar-scanner \
            -Dsonar.host.url=http://sonarqube.kcspl.in:9000/ \
            -Dsonar.login=4bfeceb86030431b89e0f94ac01e996405e8f016 \
            -Dsonar.projectKey=QulityGateTest